In [1]:
import pandas as pd

d=pd.read_csv("Telco-Customer-Churn.csv")
print(d.head())

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   Yes
3  Bank transfer (automatic)          42.30       1840.75    No
4           Electronic check          70.70        151.65   Yes

[5 rows x 21 columns]

In [3]:
d.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [7]:
pd.to_numeric(d["TotalCharges"],errors="coerce")

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [9]:
d["TotalCharges"].isnull().sum()

0

In [11]:
d.duplicated().sum()

0

In [13]:
d["Churn"].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [16]:
d.groupby("Churn")["MonthlyCharges"].mean()

Churn
No     61.265124
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [17]:
pd.crosstab(d["InternetService"],d["Churn"])

Churn              No   Yes
InternetService
DSL              1962   459
Fiber optic      1799  1297
No               1413   113

In [18]:
pd.crosstab(d["Contract"],d["Churn"])

Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48

In [19]:
for col in d.columns:
    if col != "customerID":
        print("\n", col)
        print(pd.crosstab(d[col], d["Churn"]))

 gender
Churn     No  Yes
gender
Female  2549  939
Male    2625  930

 SeniorCitizen
Churn            No   Yes
SeniorCitizen
0              4508  1393
1               666   476

 Partner
Churn      No   Yes
Partner
No       2441  1200
Yes      2733   669

 Dependents
Churn         No   Yes
Dependents
No          3390  1543
Yes         1784   326

 tenure
Churn    No  Yes
tenure
0        11    0
1       233  380
2       115  123
3       106   94
4        93   83
...     ...  ...
68       91    9
69       87    8
70      108   11
71      164    6
72      356    6

[73 rows x 2 columns]

 PhoneService
Churn           No   Yes
PhoneService
No             512   170
Yes           4662  1699

 MultipleLines
Churn               No  Yes
MultipleLines
No                2541  849
No phone service   512  170
Yes               2121  850

 InternetService
Churn              No   Yes
InternetService
DSL              1962   459
Fiber optic      1799  1297
No               1413   113

 OnlineSecurity
Churn                  No   Yes
OnlineSecurity
No                   2037  1461
No internet service  1413   113
Yes                  1724   295

 OnlineBackup
Churn                  No   Yes
OnlineBackup
No                   1855  1233
No internet service  1413   113
Yes                  1906   523

 DeviceProtection
Churn                  No   Yes
DeviceProtection
No                   1884  1211
No internet service  1413   113
Yes                  1877   545

 TechSupport
Churn                  No   Yes
TechSupport
No                   2027  1446
No internet service  1413   113
Yes                  1734   310

 StreamingTV
Churn                  No  Yes
StreamingTV
No                   1868  942
No internet service  1413  113
Yes                  1893  814

 StreamingMovies
Churn                  No  Yes
StreamingMovies
No                   1847  938
No internet service  1413  113
Yes                  1914  818

 Contract
Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48

 PaperlessBilling
Churn               No   Yes
PaperlessBilling
No                2403   469
Yes               2771  1400

 PaymentMethod
Churn                        No   Yes
PaymentMethod
Bank transfer (automatic)  1286   258
Credit card (automatic)    1290   232
Electronic check           1294  1071
Mailed check               1304   308

 MonthlyCharges
Churn           No  Yes
MonthlyCharges
18.25            1    0
18.40            1    0
18.55            1    0
18.70            2    0
18.75            1    0
...             ..  ...
118.20           1    0
118.35           0    1
118.60           2    0
118.65           1    0
118.75           1    0

[1585 rows x 2 columns]

 TotalCharges
Churn         No  Yes
TotalCharges
              11    0
100.2          1    0
100.25         0    1
100.35         1    0
100.4          0    1
...           ..  ...
997.75         1    0
998.1          1    0
999.45         0    1
999.8          1    0
999.9          1    0

[6531 rows x 2 columns]

 Churn
Churn    No   Yes
Churn
No     5174     0
Yes       0  1869

In [21]:
d.to_csv("cleaned_churn_data.csv", index=False)